### ISSUE TITLE
How to install opengapps?

### ISSUE THREAD

**Issue by lbdroid** [gabrielgagz/android_device_razer_pearlyn#1]
Attempts to install opengapps via twrp bails out with "ERROR 64: Wrong architecture". Using 7.1 arm tvstock.

**Comment by gabrielgagz** [comment]
Wait....nougat? wich twrp version are you using?

EDIT: You should use 3.1.1 for nougat...

**Comment by lbdroid** [comment]
I actually tried every version of twrp. It was completely independent of that.

Turns out that the problem is in the updater script in the opengapps. They have some changing and unreasonable dependencies on the contents of the system image, in particular, the path to the "unzip" command in the system image. For the opengapps package to install correctly, the unzip command has to be located at the path /system/bin/, but on some builds (I'm not sure if its a 7.1 thing or a characteristic of the fork you're using), it can be located elsewhere, in this case, /system/xbin/. Install worked correctly after copying the unzip command into /system/bin/.
