### ISSUE TITLE
Wake-up?

### ISSUE THREAD

**Issue by lbdroid** [gabrielgagz/android_device_razer_pearlyn#2]
For 9.0, have you made any progress on the wake-up issue? I've run my own build for 9.0, and if its been sitting for a while, it simply won't come back on without a pull of the power plug. Aside from that, it seems to be pretty serviceable, aside from not handling h265 any better than Nexus Player -- i.e., hit or miss, max 720p. Presumably software decoding?

**Comment by gabrielgagz** [comment]
h265 10bit? or 8bit? I don't have issues with 8bit, because we can use the hardware decoder

**Comment by lbdroid** [comment]
Yeah, it's probably that. I know the 805 can't do 10 bit, and it would be way too heavy to deal with in software.

**Comment by gabrielgagz** [comment]
805 doesn't support 10bit hardware decoding...so, we can't handle 10bit by software (at least properly)...

**Comment by lbdroid** [comment]
Well in any case, the point of this thread is more about the ability of the device to wake consistently. Have you got any leads on that?

**Comment by gabrielgagz** [comment]
No, is something hard to catch, probably not a kernel panic. Seems to be related to some memory leak in some how, pearlyn runs out of memory and dies (actually goes to QDL mode). Right now, im running my build on enforcing and i don't have such issue (at least for now). but is just conjectures...

**Comment by lbdroid** [comment]
I attempted to force the unit to stay awake using the don't sleep while plugged in option in the developer menu. Assuming that it actually stayed awake (the device seemed to feel a little warmer after sitting a while like that), then it doesn't seem that the problem is related to sleep at all.

And since it seems to happen even while the device is awake, it should be easy enough to dump kmsg and logcat continuously to a different server on the network, and periodically check the memory and various other stats on the board to see if something is changing. Memory leaks should be quite obvious, if that is what is happening.

**Comment by gabrielgagz** [comment]
Fixed on the test kernel branch for lineage-16:

https://github.com/gabrielgagz/android_kernel_razer_pearlyn/tree/lineage-16.0_test

(this will become the default lineage-16 branch in the future)
