### ISSUE TITLE
Simplify tree cloning with local manifests

### ISSUE THREAD

**Issue by lbdroid** [gabrielgagz/android_device_razer_pearlyn#2]
Create a file in android/.repo/local_manifests/local_manifest.xml
Initial local_manifest.xml for your project should probably look something like this;
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
<remote name="githubcom" fetch="https://github.com/" />
<project name="gabrielgagz/android_device_razer_pearlyn" path="device/razer/pearlyn" remote="githubcom" revision="cm-14.1" />
<project name="gabrielgagz/proprietary_vendor_razer_pearlyn" path="proprietary/razer/pearlyn" remote="githubcom" revision="cm-14.1" />
<project name="gabrielgagz/android_kernel_razer_pearlyn" path="kernel/razer/pearlyn" remote="githubcom" revision="cm-14.1" />
</manifest>
```

Advantages;
1) Issuing a "repo sync" will update the *entire* build tree, including those listed in the local_manifest.
2) It keeps people from having to guess at which of your repositories is the correct one to use in their build, for instance, I'm not sure if I picked the correct kernel repository for that example local_manifest.xml. If you maintain your local manifest, then those looking to build your device won't have to guess.
3) In addition to adding additional repositories to synchronize, a local manifest also allows you to *override* repositories listed in the platform default manifest using "remove-project" for some default project, and then adding a project "project" with the same path from your own repository. This is important for when you need to fork and alter something from the platform.
4) It simplifies collaboration.

It is customary to store your local manifest in a repository that is dedicated to it. For instance, google uses a repository named "manifest" for their default manifest, so I would suggest something along the lines of "pearlyn_manifest" or "android_manifest_pearlyn". You can also throw in a README to that project that explains the device architecture and build process, since this ends up being the repository that binds everything together.

**Comment by gabrielgagz** [comment]
Ok great this go to my to-do list. Feel fre to add me to hangouts if you want, maybe we can work togehter on this. The rom it's close to a release...

**Comment by lbdroid** [comment]
I'm very impressed with where you've gotten with this, given that its your first device build and you seem to be mostly working on your own. I'm actually just about to kick off another device of my own, a chinese car radio. But in addition, I am setting up a build tree for your device as well and am happy to help in any way I can.

**Comment by gabrielgagz** [comment]
Well thanks, yes i learn in the entire process. Right now i need a proper light hal for the led, and some work related to the usb port. And i hope, some day get L1 working...Just let me know and i'll add you as a collaborator

**Comment by lbdroid** [comment]
lights hal is easy. i have code for that i can add.

On Aug 11, 2017 5:01 PM, "Gabriel Gomez" <notifications@github.com> wrote:

Well thanks, yes i learn in the entire process. Right now i need a proper
light hal for the led, and some work related to the usb port. And i hope,
some day get L1 working...Just let me know and i'll add you as a
collaborator

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gabrielgagz/android_device_razer_pearlyn/issues/2#issuecomment-321917850>,
or mute the thread

**Comment by gabrielgagz** [comment]
Shouldn't be har the led in the Forge is not to complicated. I get rid of razer aditions wich control the led
