### ISSUE TITLE
Why PearlynLed and not a lights HAL?

### ISSUE THREAD

**Issue by lbdroid** [gabrielgagz/android_device_razer_pearlyn#3]
This seems a bit of a hackish way to handle lights. It seems that you're treating it much like a backlight -- i.e. on when the screen goes on, and off when the screen goes off. This can be handled by a standard lights HAL.

**Comment by gabrielgagz** [comment]
This is the way that Razer handle the Led on stock rom. I will move to a light hal some day, but right now i like the app implementation because i can use the DREAMING intents....btw, the led can't do much more that on off, i.e no rgb, no blink, etc...

**Comment by lbdroid** [comment]
Since it isn't a battery powered device, we can do software blink, and even fade. In fact, I think there are options for enabling soft blink right in the kernel, I know there definitely are on nexus 6, which is the same soc. It also didn't have hardware blink enabled in the firmware, so that was never available to it.

**Comment by gabrielgagz** [comment]
You should try. I don't want my led blinking really. I just want stock behavior, i'm fine with it...
