### ISSUE TITLE
Lights HAL

### ISSUE THREAD

**Issue by lbdroid** [gabrielgagz/android_device_razer_pearlyn#4]
I presume that when you say you have control of the LED, you mean through a kernel interface like /sys/class/leds/{something}.

That being the case, it is pretty easy to build a HAL to control it, BUT, the question is, what function should the light have?

If I recall correctly (its been a while since I've powered up my pearlyn), the LED was pretty much an ON notifier. Android doesn't define any type of light for this function.

These are the light types that Android knows about;

Screen backlight, keyboard backlight, buttons (i.e., physical or capacitive home/back buttons), battery (low, charging, charged), notifications, attention (attention is related to notifications), caps lock, and function lock.

Now some of those light types are obviously not relevant, such as anything to do with a keyboard, buttons, or battery.

Now it is also worth noting that Nexus Player (fugu) does not use a lights hal at all. Instead, they use this; "write /sys/class/leds/white/device/led_lighting_effect 1"

I'm not entirely sure what led_lighting_effect 1 means, but their code is here; https://android.googlesource.com/kernel/x86_64/+/android-x86_64-fugu-3.10-nougat-mr2/arch/x86/platform/fugu/
Note: this code is really not applicable to us.

**Comment by gabrielgagz** [comment]
Razer, in stock rom, also uses something similar. The "PearlynLed" app it has two jobs:
1) echo > 1 /proc/led_device on android.intent.action.DREAMING_STOPPED or android.intent.action.SCREEN_OFF
2) echo > 255 /proc/led_device on android.intent.action.DREAMING_STARTED or android.intent.action.SCREEN_ON

I get rid of this layer in the kernel and remove this app, becouse is broken in some how and it's a stupid layer over a real working driver. Right now the led is controled in /sys/class/leds/pearlyn
The brightness files controls the intensity. 0 is off and 255 is max.

The basic function, of course should be on/off. But i was thinking in probably extend some functionality, maybe using a half of brightness in night hours, for example, nothing too complicated.

I stared to write a basic service, wich is totally useless and incomplete...

**Comment by lbdroid** [comment]
Why don't we just make it a notification led? Its pretty useless to tie it to screen on/off, since you can see if its on or not by looking at your tv screen.

**Comment by gabrielgagz** [comment]
Sure why not? It's a great idea...now we have full control over the led....

**Comment by lbdroid** [comment]
If we set it as a notification, then its purpose is to say "hey look at me, there is something you need to address", so it doesn't necessarily mean that it shouldn't go on while the screen is off.

But point is that there are really only two things we can do with a hal; tie it to backlight (which *might* be able to tie it in to screen on/off, depending on how Android sees the screen), or notification.

**Comment by gabrielgagz** [comment]
What do we need to adress in Android TV? Probably boot up process...Maybe an update? if some day we implement unnoficial ota updates....Some music visualizer/equalizer?

**Comment by lbdroid** [comment]
There really shouldn't be much in the way of notifications on ATV, which means that it won't be needlessly harassing the user either way.

**Comment by gabrielgagz** [comment]
Well, feel free to do whatever you think about this...

**Comment by gabrielgagz** [comment]
Unil we have a better solution, is solved with CMActions:
https://github.com/gabrielgagz/android_device_razer_pearlyn/tree/cm-14.1/CMActions
