### ISSUE TITLE
Forcing Forge TV into the device mode without connecting screen

### ISSUE THREAD

**Issue by a1batross** [gabrielgagz/android_device_razer_pearlyn#5]
I don't have any HDMI-compatible screens and don't want to buy any, but still want to use Forge TV in some useful ways, like my own build server. 

I previously tried to patch kernel to force Forge TV run in device mode to have an ADB shell at least. But it seems to be not work.

Maybe there is any ideas to get it working?

**Comment by a1batross** [comment]
I also wondering, is this device tree for LOS can be used for running pure Linux distrubution instead of Android.

**Comment by gabrielgagz** [comment]
Regarding to usb "Device Mode". It's controlled by the file /proc/usb_device, a "0" in there puts the device in debug mode and an "1" puts the device in "host mode". LOS rom comes with built in adb over tcp enabled, so if you can connect the forge to an ethernet cable you have debug mode at start.
Also, with a rom with init.d support (like my adoptable mi rom or lineage) you can add an script who run thos command at start "echo 0 > /porc/usb_device" and you will have device mode on boot. 
Regarding to Linux, i never test to build a distro on the Forge (and i'm not interested), but as far i know there are several distros with arm support.  

https://www.linux.com/learn/4-fine-linux-arm-distros
https://forum.xda-developers.com/showthread.php?t=2287540

**Comment by a1batross** [comment]
I didn't knew is init.d is available here.

Thanks for usb_device and adb hint, I will try it out! :)

As far as I know, loading Linux without getting too far in Android booting process is possible with "kexec" -- separate kernel with custom cmdline can replace Android's. This is how MultiROM works.

**Comment by gabrielgagz** [comment]
There are alot of tutos how to add kexec support in the kernel in xda you can try starting from there.
Right now i'm focused in another things, but probably in a future i'll add support for this in my sources.

**Comment by lbdroid** [comment]
@a1batross : kexec won't help you. Its purpose is to switch the running kernel, which won't help you at all. All you want to do is switch the userspace, and that is done by changing the init script so that instead of starting Android, you start whatever distro you pick and install.

Keep in mind that if you kexec the kernel, you need to actually HAVE another kernel to start in its place, otherwise you are switching the running kernel with the same thing and end up at the same place where you started. That's just silly. Its also pointless, since even if you did have another kernel to run, you can just build a boot image around it, install it to the device, and call it a day. No need to kexec it to boot it.

**Comment by a1batross** [comment]
@lbdroid I guess that kernel built for Android will not work properly for typical Linux distro, so replacing kernel must help here.

**Comment by lbdroid** [comment]
You "guess"?
You guess wrong.

**Comment by a1batross** [comment]
I never tried this. I can only "guess", "assume", etc.

I will try just pass another init to kernel anyway. Thanks. :)

18 авг. 2017 г. 12:30 ДП пользователь "lbdroid" <notifications@github.com>
написал:

**Comment by gabrielgagz** [comment]
As @lbdroid says the android kernel it's a linux kernel lol
@a1batross let me know if you have success with this please, cheers

**Comment by a1batross** [comment]
@lbdroid was right. 

I almost got loading Gentoo stage3 on it. But not yet.
I have built a busybox for it with ```switch_root``` support and a minimal ramdisk with it. 
Then I have put stage3(preconfigured it to have minimal access: dhcp client and sshd) to ```userdata``` partition. ```system``` partition is small for stage3, so I plan format it and use as a "swap" partition.

At this time my Forge TV hangs to emergency mode after switch_root. I don't know, is it fails on switching or while executing new init. 

While I understand how UART works, I don't know how to read a kernel log from it. But it's a serious issue, it's just depends on my free time.

**Comment by lbdroid** [comment]
Unless you can figure out how to wire in a direct UART, your best bet for that would probably be a couple of PL2303 or similar USB-to-serial bridges hooked up in a null-modem configuration.

Then you build the kernel with that driver built-in (not as a module), and then set your "console=" kernel parameter to whatever it shows up as, i.e. "console=ttyUSB0"

Then you just set up your other machine to print out whatever comes in over its own ttyUSB using, for instance, stty.

**Comment by a1batross** [comment]
I have set a telnet access from busybox. 

For some reason, fastboot can't correctly write to ```userdata``` paritition. Trying to mount ```userdata``` just gives EINVAL. 
So I have cut off some things from stage3 image and written in ```system``` partition and finally it mounts and switches correctly. Now I am rebuilding kernel to add devtmpfs feature, which is a requirement to run "udev".

**Comment by a1batross** [comment]
So... Now I have more free time as I finished my exams. :)

Finally loaded Gentoo on it, the only requirement was devtmpfs in kernel.
